In [2]:
import pandas as pd

In [3]:
stats = pd.read_csv('../cbb/cbb25.csv')
stats = stats.drop(columns=['POSTSEASON', 'CONF', 'Unnamed: 24'])
stats

,TEAM,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,TO_DIFF
0,Alabama St.,34,19,100.5,109.6,0.2698,47.1,50.3,13.2,18.6,...,29.9,38.7,45.4,50.4,32.9,33.4,67.6,-10.20,16,4.0
1,Saint Francis U,33,16,99.9,112.0,0.2114,51.6,51.3,19.6,16.4,...,23.8,28.7,52.6,53.4,33.4,32.3,67.2,-12.20,16,-1.7
2,Mount St. Mary's,34,22,99.4,107.5,0.2903,51.0,48.0,21.7,15.9,...,31.0,26.7,50.1,48.7,34.9,31.4,67.3,-8.20,16,-3.9
3,Xavier,32,21,116.3,97.8,0.8797,53.9,50.6,16.0,17.6,...,37.2,28.1,51.3,50.5,38.8,33.9,69.0,0.35,11,1.1
4,Texas,34,19,116.7,100.2,0.8524,52.5,48.4,14.3,16.6,...,36.6,39.3,51.8,47.5,36.0,33.3,67.3,0.04,11,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Wofford,34,19,111.4,109.8,0.5422,53.3,51.8,16.9,14.9,...,31.1,36.2,54.6,51.8,34.5,34.5,64.0,-9.70,15,-0.6
64,Robert Morris,34,26,106.0,105.1,0.5265,51.3,50.3,18.5,18.8,...,38.4,30.0,50.7,49.8,34.9,34.2,68.0,-4.30,15,0.1
65,Bryant,34,23,105.9,105.4,0.5122,51.0,47.7,16.5,16.4,...,30.4,30.0,51.5,47.3,33.4,32.2,72.4,-7.10,15,0.1
66,Norfolk St.,34,24,106.4,109.1,0.4276,52.4,49.7,18.3,18.6,...,39.0,34.9,54.5,48.9,31.3,33.9,66.4,-5.30,16,0.8
67,SIU Edwardsville,33,22,101.5,105.8,0.3822,48.9,47.5,17.1,17.3,...,33.1,33.2,47.8,46.3,34.0,33.0,65.9,-7.80,16,1.3

In [4]:
matchups = pd.read_csv('../mm/mm/mm25.csv')
matchups

,winner,SEED_higher,SEED_lower,TEAM_higher,G_higher,W_higher,ADJOE_higher,ADJDE_higher,BARTHAG_higher,EFG_O_higher,...,FTR_lower,FTRD_lower,2P_O_lower,2P_D_lower,3P_O_lower,3P_D_lower,ADJ_T_lower,WAB_lower,SEED_lower.1,Turnover_diff_lower
0,NaN,NaN,NaN,Auburn,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Louisville,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,Michigan,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Texas A&M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,Mississippi,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,Iowa St.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,Marquette,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,Michigan St.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,Florida,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,Connecticut,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,Memphis,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,Maryland,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,Missouri,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,Texas Tech,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,Kansas,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,St. John's,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,Florida,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,Maryland,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,Texas Tech,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,St. John's,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,Auburn,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,Texas A&M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,Iowa St.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,Michigan St.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,Duke,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,Mississippi St.,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,Oregon,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,Arizona,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,BYU,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,Saint Mary's,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,Duke,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,Arizona,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,Houston,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,Gonzaga,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,Clemson,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,Purdue,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,Illinois,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,Kentucky,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,UCLA,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,Tennessee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,Houston,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,Purdue,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,Kentucky,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,Tennessee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# row[4:25]
# teamHigh.iloc[:, 1:]
matchups = pd.read_csv('../mm/mm/mm25.csv')
for index, row in matchups.iterrows():
    teamHigh = stats.loc[stats['TEAM'] == row['TEAM_higher']]
    teamLow = stats.loc[stats['TEAM'] == row['TEAM_lower']]

    matchups['SEED_higher'].iloc[index] = teamHigh['SEED']
    matchups['G_higher'].iloc[index] = teamHigh['G']
    matchups['W_higher'].iloc[index] = teamHigh['W']
    matchups['ADJOE_higher'].iloc[index] = teamHigh['ADJOE']
    matchups['ADJDE_higher'].iloc[index] = teamHigh['ADJDE']
    matchups['BARTHAG_higher'].iloc[index] = teamHigh['BARTHAG']
    matchups['EFG_O_higher'].iloc[index] = teamHigh['EFG_O']
    matchups['EFG_D_higher'].iloc[index] = teamHigh['EFG_D']
    matchups['TOR_higher'].iloc[index] = teamHigh['TOR']
    matchups['TORD_higher'].iloc[index] = teamHigh['TORD']
    matchups['ORB_higher'].iloc[index] = teamHigh['ORB']
    matchups['DRB_higher'].iloc[index] = teamHigh['DRB']
    matchups['FTR_higher'].iloc[index] = teamHigh['FTR']
    matchups['FTRD_higher'].iloc[index] = teamHigh['FTRD']
    matchups['2P_O_higher'].iloc[index] = teamHigh['2P_O']
    matchups['2P_D_higher'].iloc[index] = teamHigh['2P_D']
    matchups['3P_O_higher'].iloc[index] = teamHigh['3P_O']
    matchups['3P_D_higher'].iloc[index] = teamHigh['3P_D']
    matchups['ADJ_T_higher'].iloc[index] = teamHigh['ADJ_T']
    matchups['WAB_higher'].iloc[index] = teamHigh['WAB']
    matchups['Turnover_diff_higher'].iloc[index] = teamHigh['TO_DIFF']


    matchups['SEED_lower'].iloc[index] = teamLow['SEED']
    matchups['G_lower'].iloc[index] = teamLow['G']
    matchups['W_lower'].iloc[index] = teamLow['W']
    matchups['ADJOE_lower'].iloc[index] = teamLow['ADJOE']
    matchups['ADJDE_lower'].iloc[index] = teamLow['ADJDE']
    matchups['BARTHAG_lower'].iloc[index] = teamLow['BARTHAG']
    matchups['EFG_O_lower'].iloc[index] = teamLow['EFG_O']
    matchups['EFG_D_lower'].iloc[index] = teamLow['EFG_D']
    matchups['TOR_lower'].iloc[index] = teamLow['TOR']
    matchups['TORD_lower'].iloc[index] = teamLow['TORD']
    matchups['ORB_lower'].iloc[index] = teamLow['ORB']
    matchups['DRB_lower'].iloc[index] = teamLow['DRB']
    matchups['FTR_lower'].iloc[index] = teamLow['FTR']
    matchups['FTRD_lower'].iloc[index] = teamLow['FTRD']
    matchups['2P_O_lower'].iloc[index] = teamLow['2P_O']
    matchups['2P_D_lower'].iloc[index] = teamLow['2P_D']
    matchups['3P_O_lower'].iloc[index] = teamLow['3P_O']
    matchups['3P_D_lower'].iloc[index] = teamLow['3P_D']
    matchups['ADJ_T_lower'].iloc[index] = teamLow['ADJ_T']
    matchups['WAB_lower'].iloc[index] = teamLow['WAB']
    matchups['Turnover_diff_lower'].iloc[index] = teamLow['TO_DIFF']

C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['SEED_higher'].iloc[index] = teamHigh['SEED']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['SEED_higher'].iloc[index] = teamHigh['SEED']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['G_higher'].iloc[index] = teamHigh['G']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['G_higher'].iloc[index] = teamHigh['G']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['W_higher'].iloc[index] = teamHigh['W']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['W_higher'].iloc[index] = teamHigh['W']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['ADJOE_higher'].iloc[index] = teamHigh['ADJOE']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['ADJOE_higher'].iloc[index] = teamHigh['ADJOE']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['ADJDE_higher'].iloc[index] = teamHigh['ADJDE']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['ADJDE_higher'].iloc[index] = teamHigh['ADJDE']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['BARTHAG_higher'].iloc[index] = teamHigh['BARTHAG']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['BARTHAG_higher'].iloc[index] = teamHigh['BARTHAG']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:14: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['EFG_O_higher'].iloc[index] = teamHigh['EFG_O']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['EFG_O_higher'].iloc[index] = teamHigh['EFG_O']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:15: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['EFG_D_higher'].iloc[index] = teamHigh['EFG_D']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['EFG_D_higher'].iloc[index] = teamHigh['EFG_D']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:16: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['TOR_higher'].iloc[index] = teamHigh['TOR']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['TOR_higher'].iloc[index] = teamHigh['TOR']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:17: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['TORD_higher'].iloc[index] = teamHigh['TORD']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['TORD_higher'].iloc[index] = teamHigh['TORD']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:18: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['ORB_higher'].iloc[index] = teamHigh['ORB']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['ORB_higher'].iloc[index] = teamHigh['ORB']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['DRB_higher'].iloc[index] = teamHigh['DRB']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['DRB_higher'].iloc[index] = teamHigh['DRB']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:20: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['FTR_higher'].iloc[index] = teamHigh['FTR']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['FTR_higher'].iloc[index] = teamHigh['FTR']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:21: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['FTRD_higher'].iloc[index] = teamHigh['FTRD']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['FTRD_higher'].iloc[index] = teamHigh['FTRD']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:22: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  matchups['2P_O_higher'].iloc[index] = teamHigh['2P_O']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matchups['2P_O_higher'].iloc[index] = teamHigh['2P_O']
C:\Users\prest\AppData\Local\Temp\ipykernel_1300\450625310.py:23: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.


ValueError: setting an array element with a sequence.

In [ ]:
matchups.to_csv('matchups25.csv', index=False)