In [31]:
import pandas as pd

Get CSV of current season stats

In [32]:
stats = pd.read_csv('cbb/cbb26.csv')
stats = stats.drop(columns=['POSTSEASON', 'CONF', 'Unnamed: 24'])
stats

,TEAM,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,TORD,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,TO_DIFF
0,UMBC,32,24,107.6,109.2,0.4555,53.9,49.2,14.1,15.2,...,33.8,25.2,54.0,49.7,35.9,32.2,66.0,-5.10,16,0.7
1,Howard,33,23,103.4,106.2,0.4240,50.6,47.4,19.8,21.3,...,44.2,38.3,49.9,48.3,34.7,30.4,69.0,-6.90,16,1.5
2,Texas,32,18,124.1,106.4,0.8541,54.2,51.2,15.3,13.4,...,46.2,40.7,55.3,49.8,34.9,36.0,67.1,-0.21,11,-1.6
3,NC State,33,20,124.1,104.6,0.8766,55.3,53.0,13.1,18.2,...,35.2,36.5,53.1,52.7,38.8,35.6,69.1,0.34,11,3.5
4,Lehigh,34,18,102.6,112.8,0.2516,53.3,50.6,17.5,16.3,...,32.2,32.8,52.4,51.2,36.5,32.8,66.9,-12.00,16,-0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,Wright St.,34,23,112.4,109.0,0.5864,54.4,52.1,16.3,16.5,...,38.0,33.5,54.5,52.9,36.1,33.6,67.0,-6.60,14,0.7
64,Kentucky,34,21,119.9,100.0,0.8900,53.1,48.8,15.0,15.8,...,37.5,37.0,54.4,49.6,34.1,31.6,68.3,3.30,7,0.6
65,Santa Clara,34,26,125.0,103.7,0.8952,54.6,51.8,15.6,20.1,...,25.8,38.3,56.5,53.2,34.9,33.0,69.3,2.10,10,3.2
66,Iowa St.,34,27,123.8,92.6,0.9655,56.5,49.5,15.1,22.4,...,34.0,27.9,55.5,50.5,38.7,32.1,67.0,7.40,2,5.0
67,Tennessee St.,32,23,107.8,111.9,0.3944,50.1,51.2,16.5,20.0,...,33.5,41.6,49.9,51.8,33.7,33.5,70.1,-5.70,15,2.5

Get the Matchups you with to predict

In [33]:
matchups = pd.read_csv('mm/mm26.csv')
matchups

,winner,SEED_higher,SEED_lower,TEAM_higher,G_higher,W_higher,ADJOE_higher,ADJDE_higher,BARTHAG_higher,EFG_O_higher,...,FTR_lower,FTRD_lower,2P_O_lower,2P_D_lower,3P_O_lower,3P_D_lower,ADJ_T_lower,WAB_lower,SEED_lower.1,Turnover_diff_lower
0,NaN,NaN,NaN,Arizona,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Inserts missing stats of the team matchups

In [34]:
matchups = pd.read_csv('mm/mm26.csv')
for index, row in matchups.iterrows():
    # location of the team based on seed
    teamHigh = stats.loc[stats['TEAM'] == row['TEAM_higher']]
    if len(teamHigh) == 1:
        # add the data of the higher seed team
        matchups.at[index, 'SEED_higher']= teamHigh['SEED'].iloc[0]
        matchups.at[index,'G_higher'] = teamHigh['G'].iloc[0]
        matchups.at[index,'W_higher'] = teamHigh['W'].iloc[0]
        matchups.at[index,'ADJOE_higher'] = teamHigh['ADJOE'].iloc[0]
        matchups.at[index,'ADJDE_higher'] = teamHigh['ADJDE'].iloc[0]
        matchups.at[index,'BARTHAG_higher'] = teamHigh['BARTHAG'].iloc[0]
        matchups.at[index,'EFG_O_higher'] = teamHigh['EFG_O'].iloc[0]
        matchups.at[index,'EFG_D_higher'] = teamHigh['EFG_D'].iloc[0]
        matchups.at[index,'TOR_higher'] = teamHigh['TOR'].iloc[0]
        matchups.at[index,'TORD_higher'] = teamHigh['TORD'].iloc[0]
        matchups.at[index,'ORB_higher'] = teamHigh['ORB'].iloc[0]
        matchups.at[index,'DRB_higher'] = teamHigh['DRB'].iloc[0]
        matchups.at[index,'FTR_higher'] = teamHigh['FTR'].iloc[0]
        matchups.at[index,'FTRD_higher'] = teamHigh['FTRD'].iloc[0]
        matchups.at[index,'2P_O_higher'] = teamHigh['2P_O'].iloc[0]
        matchups.at[index,'2P_D_higher'] = teamHigh['2P_D'].iloc[0]
        matchups.at[index,'3P_O_higher'] = teamHigh['3P_O'].iloc[0]
        matchups.at[index,'3P_D_higher'] = teamHigh['3P_D'].iloc[0]
        matchups.at[index,'ADJ_T_higher'] = teamHigh['ADJ_T'].iloc[0]
        matchups.at[index,'WAB_higher'] = teamHigh['WAB'].iloc[0]
        matchups.at[index,'Turnover_diff_higher'] = teamHigh['TO_DIFF'].iloc[0]
    else:
        print(teamHigh, "higher", index)

    # add the data of the lower seed team
    teamLow = stats.loc[stats['TEAM'] == row['TEAM_lower']]
    if len(teamLow) == 1:
        matchups.at[index, 'SEED_lower']= teamLow['SEED'].iloc[0]
        matchups.at[index,'G_lower'] = teamLow['G'].iloc[0]
        matchups.at[index,'W_lower'] = teamLow['W'].iloc[0]
        matchups.at[index,'ADJOE_lower'] = teamLow['ADJOE'].iloc[0]
        matchups.at[index,'ADJDE_lower'] = teamLow['ADJDE'].iloc[0]
        matchups.at[index,'BARTHAG_lower'] = teamLow['BARTHAG'].iloc[0]
        matchups.at[index,'EFG_O_lower'] = teamLow['EFG_O'].iloc[0]
        matchups.at[index,'EFG_D_lower'] = teamLow['EFG_D'].iloc[0]
        matchups.at[index,'TOR_lower'] = teamLow['TOR'].iloc[0]
        matchups.at[index,'TORD_lower'] = teamLow['TORD'].iloc[0]
        matchups.at[index,'ORB_lower'] = teamLow['ORB'].iloc[0]
        matchups.at[index,'DRB_lower'] = teamLow['DRB'].iloc[0]
        matchups.at[index,'FTR_lower'] = teamLow['FTR'].iloc[0]
        matchups.at[index,'FTRD_lower'] = teamLow['FTRD'].iloc[0]
        matchups.at[index,'2P_O_lower'] = teamLow['2P_O'].iloc[0]
        matchups.at[index,'2P_D_lower'] = teamLow['2P_D'].iloc[0]
        matchups.at[index,'3P_O_lower'] = teamLow['3P_O'].iloc[0]
        matchups.at[index,'3P_D_lower'] = teamLow['3P_D'].iloc[0]
        matchups.at[index,'ADJ_T_lower'] = teamLow['ADJ_T'].iloc[0]
        matchups.at[index,'WAB_lower'] = teamLow['WAB'].iloc[0]
        matchups.at[index,'Turnover_diff_lower'] = teamLow['TO_DIFF'].iloc[0]
    else:
        print(teamLow, "Lower", index)

In [35]:
matchups.to_csv('matchups26.csv', index=False)